name: PostgresWithAPIWithAngular
services:
  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: DockerFile
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  apiread:
    container_name: apiread
    depends_on:
      - postgres
    build:
      context: ./apiRead
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      

  apiwrite:
    container_name: apiwrite
    depends_on:
      - postgres
    build:
      context: ./apiWrite
      dockerfile: Dockerfile
    ports:
      - "5237:8080"

  angular:
    container_name: angular
    depends_on:
      - apiread
    build:
      context: ./angular/MovieAngular
      dockerfile: DockerFile
    ports:
      - "42000:8080"

networks:
  back:
    internal: true
  middle:
    internal: true
  front:
